### PR TITLE
Nixify the project

### PR DESCRIPTION
**Pull request by srid**
No obligation to merge this! I had to nixify just so I could try it locally on my Mac.

- [x] `nix run` works.
- [x] After https://github.com/lucasvreis/org-parser/pull/4 is merged, switch over the flake input back to upstream
- [ ] Should I add GitHub Actions (analogous to https://github.com/srid/emanote/blob/master/.github/workflows/ci.yaml)?

### CODE REVIEW

**Comment by GTrunSec** [comment]
Thank you very much and @lucasvreis for your work on this. Impressed with your ema project too. I wish to be able to use abacateiro as publishing of some normalized org-roam documentation. Like this https://github.com/GTrunSec/org-roam-book-template

**Comment by srid** [comment]
For whatever reason, I'm unable to get HLS to work. It complains about mismatch in `time` dependency, which is strange because `org-parser` no longer has the `>=1.10` constraint. No idea where it is coming from.

image

**Comment by lua-vr** [comment]
@srid maybe because there is a `cabal.project` file in abacateiro that wasn't updated to the latest org-parser commit? (~~can you update it in the PR?~~ done)

**Comment by srid** [comment]
Hmm, right. Though, after your change (the force push), the error just appears on a different package:

image

When I remove `cabal.project` entirely it works (as far as Nix based development is concerned, the source-overrides in cabal.project become unnecessary).

---

But none of this matters much if you don't use Nix for development. I do wonder how we can make ~~Nix~~ HLS-installed-via-Nix happy by having it ignore the overrides in cabal.project.

**Comment by GTrunSec** [comment]
>When I remove cabal.project entirely it works (as far as Nix based development is concerned, the source-overrides in cabal.project become unnecessary).

If this worked, why not use runCommand to modify the src source or nix-filter?

**Comment by srid** [comment]
> > When I remove cabal.project entirely it works (as far as Nix based development is concerned, the source-overrides in cabal.project become unnecessary).
> 
> If this worked, why not use runCommand to modify the src source or nix-filter?

I do not believe that will help, because `haskell-language-server` is running in a nix shell (ie. not a nix build).

**Pull request closed without merging**
